FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app

# Create folder structure to match package
RUN mkdir -p src/application

# Copy files into correct folder
COPY src/application/*.java src/application/

# Compile with folder structure
RUN javac src/application/*.java

# Run with full package name
CMD ["java", "-cp", "src", "application.App"]
